### ISSUE TITLE
pIrony

### ISSUE THREAD

**Issue by reichley** [jamesacampbell/findpi#1]
When run from a pi, a user would first need to install Python3.6 since it's not yet in the raspbian distro and the script fails on the new string formatting 'f'.
https://gist.github.com/reichley/1d0ce781adb3f7f0abe4e4a680c961e6

Also, as an FYI, if run from a pi this script doesn't actually identify/return the result to the script since the ```nmap -sP {ipaddress}``` doesn't return a MAC address in the result.

Feel free to close...just an info issue.

**Comment by james-see** [comment]
Yeah, you need to run it as sudo to get the mac addresses, which is stated in readme. I can make that clearer. Also it is actually python 3.7 that is required for the new f string formats. I guess i can change it to be .format which would only require 3.x or just basic string formatting from 2.x to be compatible. Thanks for trying it and try it as sudo to see if it works properly.

**Comment by reichley** [comment]
I'm aware of the ```sudo``` requirement. I was just stating that the IP of the host running the ```nmap -sP``` command doesn't return a MAC address...so if it's a raspberry pi the script wouldn't find it. [PEP 498](https://www.python.org/dev/peps/pep-0498/) (Python 3.6) introduced "f" formatting strings. You're welcome, man.

**Comment by james-see** [comment]
Ah, gotcha, I understand, wasn't thinking a pi itself would be running it on the network and then of course, yes, would self-identify too.
