### ISSUE TITLE
crashes without -c option

### ISSUE THREAD

**Issue by HowardALandman** [jamesacampbell/findpi#13]
On both Raspbian Buster on a Pi4 1.1, and Raspbian Lite Buster on a Pi0W 1.1, findpi 1.1.0 crashes in `checkCores()` (findpy.py line 81) where it's using /proc/cpuinfo to try to figure out the number of cores. If I run it as `findpi -c 4` so that it doesn't need to figure it out, everything works fine.

**Comment by james-see** [comment]
@HowardALandman thanks for reporting this, is there a better check to use instead of cpuinfo to mitigate this?

**Comment by HowardALandman** [comment]
> On Jun 22, 2020, at 2:01 PM, JC <notifications@github.com> wrote:
> @HowardALandman <https://github.com/HowardALandman> thanks for reporting this, is there a better check to use instead of cpuinfo to mitigate this?
> 
I think you should be able to get the info you need from /proc/cpuinfo, just count up the “Processor” lines. But you probably want to put it in a “try” block to be safe:

f_name = "/proc/cpuinfo"
try:
    with open(f_name) as cpu_info_file:
        # success stuff here, reading from cpu_info_file
except IOError:
    print(“Couldn’t open”, f_name)
    # failure stuff here

The “with” clause is nice because it cleans up after itself (e.g. it closes the file automatically if it fails).

    Howard

**Comment by james-see** [comment]
> On Jun 22, 2020, at 2:01 PM, JC ***@***.***> wrote: @HowardALandman <https://github.com/HowardALandman> thanks for reporting this, is there a better check to use instead of cpuinfo to mitigate this?
> I think you should be able to get the info you need from /proc/cpuinfo, just count up the “Processor” lines. But you probably want to put it in a “try” block to be safe: f_name = "/proc/cpuinfo" try: with open(f_name) as cpu_info_file: # success stuff here, reading from cpu_info_file except IOError: print(“Couldn’t open”, f_name) # failure stuff here The “with” clause is nice because it cleans up after itself (e.g. it closes the file automatically if it fails). Howard

Great, it looks like I can update the command to be `cat /proc/cpuinfo | grep processor | wc -l` which returns int 4 in my case. I can just wrap that in a try and go from there. I am pushing an updated version tonight and will close referencing this issue. Please file another one if you find anything amiss. 

I would also like general feedback on your use case, I want to add other features and options and curious to hear any general uses you have.

**Comment by HowardALandman** [comment]
> On Jun 22, 2020, at 8:58 PM, JC <notifications@github.com> wrote:
> Great, it looks like I can update the command to be cat /proc/cpuinfo | grep processor | wc -l which returns int 4 in my case.
> 
You know you can do all that in a couple of lines of Python instead of spawning 3 external programs, right? :-) It’s easy to fall back on the UNIX commands we know and understand … as a dinosaur UNIX user since the 1970s, I often do it myself … but sometimes it’s also good to consider “the Python way” and try to follow that. It’s helped me to get more comfortable and fluent in the language.
> I would also like general feedback on your use case, I want to add other features and options and curious to hear any general uses you have.
> 

I usually want to find all the Pis on the local wifi subnet (256 addresses), i.e. the default /24 is fine. This typically takes 45 to 90 seconds.

    Howard
