### ISSUE TITLE
"findpi —help" and "findpi —version" won’t run without sudo.

### ISSUE THREAD

**Issue by HowardALandman** [jamesacampbell/findpi#17]
`findpi —help` won’t run without sudo. That seems unnecessary and slightly user-hostile. The check for privilege should only happen if you need it.

`findpi —version` also won’t run without sudo, which could be a separate issue, but I suspect that the fix is the same in both cases.

Both tested using version 1.1.0 on a Rpi4 1.1 running Raspian Buster.

**Comment by james-see** [comment]
@HowardALandman yes, I basically call to thec check_sudo function before I call main which would compile the arguments in argparse object. I was waffling between this, but I agree, why not let argparse at least run before letting the user know they need sudo. I will update.

**Comment by james-see** [comment]
@HowardALandman fixed in 1.1.4 available in pypi now. Thanks!
